### ISSUE TITLE
Tutorial 2 issues

### ISSUE THREAD

**Issue by DenysVuika** [naodroid/bevy_game_tutorial#1]
Code from tutorial 2 is not working.

Expects:

```
## Print ##
 Block-1
 Block-10
```

Actual Result:

```
## Print ##
```

I check the [code](https://github.com/naodroid/bevy_game_tutorial/blob/master/src/tutorial02.rs), and there's a difference in the Block struct

```
// tutorial
struct Block(i32);

// code
struct Block;
```

With that code, the output however is:

```
## Print ##
 Block-20
```

which is also incorrect

**Comment by naodroid** [comment]
Thank you for pointing it out. I fixed it in c8c1dddbceac854ba1ab19c61c51e6f86e11eedf
